# Generated by Django 3.0.3 on 2020-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sympthoms',
        ),
    ]
