# Generated by Django 3.0.7 on 2020-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200607_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.ImageField(max_length=300, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
