# Generated by Django 3.0.7 on 2020-06-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20200607_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
