# Generated by Django 3.0.7 on 2020-06-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20200608_1308'),
        ('trade', '0004_auto_20200608_1210'),
    ]

    operations = [
    ]
